set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR i386)

set(CMAKE_C_COMPILER i386-apple-darwin15-clang)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_AR "i386-apple-darwin15-ar" CACHE FILEPATH "ar")
set(CMAKE_RANLIB "i386-apple-darwin15-ranlib" CACHE FILEPATH "ranlib")
set(CMAKE_INSTALL_NAME_TOOL "i386-apple-darwin15-install_name_tool"
	CACHE FILEPATH "install_name_tool")
