stages:
  - analyse
  - build
  - test
  - doc
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal

clang_format:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/clang_format:1.0
  script:
    - ./ci/clang_format.sh check

clang_tidy:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/clang_tidy:1.1
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCLANG_TIDY:BOOL=ON -DTEST:BOOL=ON
      -DWERROR:BOOL=ON ..
    - make -j $(nproc)

cppcheck:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/cppcheck:1.0
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCPPCHECK:BOOL=ON -DWERROR:BOOL=ON
      ..
    - make cppcheck

doxygen:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/doxygen:1.0
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DDOC:STRING=doxygen -DWERROR:BOOL=ON ..
    - make doc

line_limit:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/coreutils:1.1
  script:
    - ./ci/style/line_limit.sh -e '^\.clang-tidy$' -e '^include/' -e '^src/'
      -e '^test/' -i .
    - ./ci/style/line_limit.sh include
    - ./ci/style/line_limit.sh src
    - ./ci/style/line_limit.sh test

regex_check:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/coreutils:1.1
  script:
    - ./ci/style/regex_check.sh -e '^cmake/apidoc\.py:9:' .

clang:
  stage: build
  image: git.mel.vin:5005/template/c/ci/clang:1.0
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j $(nproc)

gcc:
  stage: build
  image: git.mel.vin:5005/template/c/ci/gcc:1.0
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j $(nproc)

clang_release:
  stage: test
  image: git.mel.vin:5005/template/c/ci/clang:1.0
  script:
    - mkdir build
    - cd build
    - cmake -DTEST:BOOL=ON ..
    - make -j $(nproc)
    - make test

gcc_coverage:
  stage: test
  image: git.mel.vin:5005/template/c/ci/gcc_coverage:1.0
  coverage: '/^ *lines\.+: (\d+\.\d+\%) \(\d+ of \d+ lines\)$/'
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCOVERAGE:BOOL=ON -DTEST:BOOL=ON ..
    - make -j $(nproc)
    - make test
    - make coverage_report
  artifacts:
    paths:
      - build/coverage_report

sphinx_html:
  stage: doc
  dependencies: []
  image: git.mel.vin:5005/template/c/ci/sphinx_html:1.2
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DDOC:STRING=html -DWERROR:BOOL=ON ..
    - make doc
  artifacts:
    paths:
      - build/doc/sphinx/html

sphinx_latexpdf:
  stage: doc
  dependencies: []
  image: git.mel.vin:5005/template/c/ci/sphinx_latexpdf:1.0
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DDOC:STRING=latexpdf -DWERROR:BOOL=ON ..
    - make doc
    - mv doc/sphinx/latex/c_template.pdf ..
  artifacts:
    paths:
      - c_template.pdf

review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  only:
    - branches
  dependencies:
    - gcc_coverage
    - sphinx_html
  image: git.mel.vin:5005/template/c/ci/coreutils:1.1
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://doc.mel.vin/template/c/$CI_ENVIRONMENT_SLUG
    on_stop: review_stop
  script:
    - mkdir -p ~/.ssh
    - echo "$DOC_SSH_KNOWNHOSTS" > ~/.ssh/known_hosts
    - eval $(ssh-agent)
    - echo "$DOC_SSH_KEY" | ssh-add - >/dev/null
    - mv build/doc/html public
    - mv build/coverage_report public/coverage
    - rsync -a --delete public/ doc@mel.vin:~/template/c/$CI_ENVIRONMENT_SLUG

review_stop:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  when: manual
  dependencies: []
  image: git.mel.vin:5005/template/c/ci/coreutils:1.1
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  script:
    - mkdir -p ~/.ssh
    - echo "$DOC_SSH_KNOWNHOSTS" > ~/.ssh/known_hosts
    - eval $(ssh-agent)
    - echo "$DOC_SSH_KEY" | ssh-add - >/dev/null
    - mkdir /tmp/empty
    - rsync -a --delete --filter="+ $CI_ENVIRONMENT_SLUG" --filter='-,p *'
      /tmp/empty/ doc@mel.vin:~/template/c
    - rmdir /tmp/empty

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  only:
    - tags
  dependencies:
    - gcc_coverage
    - sphinx_html
  image: busybox:latest
  script:
    - mv build/doc/sphinx/html public
    - mv build/coverage_report public/coverage
  artifacts:
    paths:
      - public
