image: git.mel.vin:5005/template/c:ci

stages:
  - analyse
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: normal

clang_tidy:
  stage: analyse
  allow_failure: true
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCLANG_TIDY:BOOL=ON
      -DWERROR:BOOL=ON -DTEST:BOOL=ON ..
    - make -j $(nproc)

cppcheck:
  stage: analyse
  allow_failure: true
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug ..
    - cd ..
    - cppcheck -q --enable=all --project=build/compile_commands.json
      --error-exitcode=1 --suppressions-list=.cppcheck-suppress

build:clang:
  stage: build
  script:
    - mkdir build
    - cd build
    - CC=clang-6.0 cmake ..
    - make -j $(nproc)

build:gcc:
  stage: build
  script:
    - mkdir build
    - cd build
    - CC=gcc cmake ..
    - make -j $(nproc)

test:clang:
  stage: test
  script:
    - mkdir build
    - cd build
    - CC=clang-6.0 CXX=clang++-6.0 cmake -DTEST:BOOL=ON
      -DCMAKE_BUILD_TYPE:STRING=Debug -DCOVERAGE:BOOL=ON ..
    - make -j $(nproc)
    - make test
    - make coverage_report

test:gcc:
  stage: test
  script:
    - mkdir build
    - cd build
    - CC=gcc CXX=g++ cmake -DTEST:BOOL=ON
      -DCMAKE_BUILD_TYPE:STRING=Debug -DCOVERAGE:BOOL=ON ..
    - make -j $(nproc)
    - make test
    - make coverage_report
