stages:
  - analyse
  - build
  - test
  - doc
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal

clang_format:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/clang_format:1.1
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DFORMAT:BOOL=ON -DWERROR:BOOL=ON ..
    - make format_check

clang_tidy:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/clang_tidy:1.2
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCLANG_TIDY:BOOL=ON -DTEST:BOOL=ON
      -DWERROR:BOOL=ON ..
    - make -j $(nproc)

doxygen:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/doxygen:1.1
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DDOC:STRING=doxygen -DWERROR:BOOL=ON ..
    - make doc

flawfinder:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/flawfinder:1.1
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DFLAWFINDER:BOOL=ON -DWERROR:BOOL=ON ..
    - make flawfinder

line_limit:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/coreutils:1.2
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DLINE_LIMIT:BOOL=ON -DWERROR:BOOL=ON ..
    - make line_limit

regex_check:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/coreutils:1.2
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DREGEX_CHECK:BOOL=ON -DWERROR:BOOL=ON ..
    - make regex_check

clang:
  stage: build
  only:
    - master
  image: git.mel.vin:5005/template/c/ci/clang:1.1
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j $(nproc)

gcc:
  stage: build
  only:
    - master
  image: git.mel.vin:5005/template/c/ci/gcc:1.0
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j $(nproc)

clang_sanitise:
  stage: test
  image: git.mel.vin:5005/template/c/ci/clang_tidy:1.2
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DSANITISE:BOOL=ON -DTEST:BOOL=ON
      -DWERROR:BOOL=ON ..
    - make -j $(nproc)
    - make test

gcc_coverage:
  stage: test
  image: git.mel.vin:5005/template/c/ci/gcc_coverage:1.1
  coverage: '/^ *lines\.+: (\d+\.\d+\%) \(\d+ of \d+ lines\)$/'
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCOVERAGE:BOOL=ON -DTEST:BOOL=ON
      -DWERROR:BOOL=ON ..
    - make -j $(nproc)
    - make test
    - make coverage_report
  artifacts:
    paths:
      - build/coverage_report

sphinx_html:
  stage: doc
  dependencies: []
  image: git.mel.vin:5005/template/c/ci/sphinx_html:1.5
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DDOC:STRING=html -DWERROR:BOOL=ON ..
    - make doc
  artifacts:
    paths:
      - build/doc/html

review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  only:
    - branches
  dependencies:
    - gcc_coverage
    - sphinx_html
  image: git.mel.vin:5005/template/c/ci/coreutils:1.2
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://doc.mel.vin/template/c/$CI_ENVIRONMENT_SLUG
    on_stop: review_stop
  script:
    - mkdir -p ~/.ssh
    - echo "$DOC_SSH_KNOWNHOSTS" > ~/.ssh/known_hosts
    - eval $(ssh-agent)
    - echo "$DOC_SSH_KEY" | ssh-add - >/dev/null
    - mv build/doc/html public
    - mv build/coverage_report public/coverage
    - rsync -a --delete public/ doc@mel.vin:~/template/c/$CI_ENVIRONMENT_SLUG

review_stop:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  when: manual
  dependencies: []
  image: git.mel.vin:5005/template/c/ci/coreutils:1.2
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  script:
    - mkdir -p ~/.ssh
    - echo "$DOC_SSH_KNOWNHOSTS" > ~/.ssh/known_hosts
    - eval $(ssh-agent)
    - echo "$DOC_SSH_KEY" | ssh-add - >/dev/null
    - mkdir /tmp/empty
    - rsync -a --delete --filter="+ $CI_ENVIRONMENT_SLUG" --filter='-,p *'
      /tmp/empty/ doc@mel.vin:~/template/c
    - rmdir /tmp/empty

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  only:
    - tags
  dependencies:
    - gcc_coverage
    - sphinx_html
  image: busybox:latest
  script:
    - mv build/doc/html public
    - mv build/coverage_report public/coverage
  artifacts:
    paths:
      - public
