stages:
  - analyse
  - build
  - test
  - doc
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal

clang_format:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/clang_format:1.0
  script:
    - ./ci/clang_format.sh check

clang_tidy:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/clang_tidy:1.1
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCLANG_TIDY:BOOL=ON -DTEST:BOOL=ON
      -DWERROR:BOOL=ON ..
    - make -j $(nproc)

cppcheck:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/cpp/ci/cppcheck:1.0
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCPPCHECK:BOOL=ON -DWERROR:BOOL=ON
      ..
    - make cppcheck

doxygen:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/doxygen:1.0
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DDOC:STRING=doxygen -DWERROR:BOOL=ON ..
    - make doc

line_limit:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/coreutils:1.0
  script:
    - ./ci/style/line_limit.sh -e '^\.clang-tidy$' -e '^include/' -e '^src/'
      -e '^test/' -i .
    - ./ci/style/line_limit.sh include
    - ./ci/style/line_limit.sh src
    - ./ci/style/line_limit.sh test

regex_check:
  stage: analyse
  allow_failure: true
  image: git.mel.vin:5005/template/c/ci/coreutils:1.0
  script:
    - ./ci/style/regex_check.sh -e '^cmake/apidoc\.py:9:' .

clang:
  stage: build
  image: git.mel.vin:5005/template/c/ci/clang:1.0
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j $(nproc)

gcc:
  stage: build
  image: git.mel.vin:5005/template/cpp/ci/gcc:1.0
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j $(nproc)

clang_release:
  stage: test
  image: git.mel.vin:5005/template/c/ci/clang:1.0
  script:
    - mkdir build
    - cd build
    - cmake -DTEST:BOOL=ON ..
    - make -j $(nproc)
    - make test

gcc_coverage:
  stage: test
  image: git.mel.vin:5005/template/c/ci/gcc_coverage:1.0
  coverage: '/^ *lines\.+: (\d+\.\d+\%) \(\d+ of \d+ lines\)$/'
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCOVERAGE:BOOL=ON -DTEST:BOOL=ON ..
    - make -j $(nproc)
    - make test
    - make coverage_report
  artifacts:
    paths:
      - build/coverage_report

sphinx_html:
  stage: doc
  dependencies: []
  image: git.mel.vin:5005/template/c/ci/sphinx_html:1.1
  script:
    - mkdir build
    - cd build
    - cmake -DCODE:BOOL=OFF -DDOC:STRING=html -DWERROR:BOOL=ON ..
    - make doc
  artifacts:
    paths:
      - build/doc/html

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - gcc_coverage
    - sphinx_html
  image: busybox:latest
  script:
    - mv build/doc/html public
    - mv build/coverage_report public/coverage
  artifacts:
    paths:
      - public
