image: git.mel.vin:5005/template/c:ci

stages:
  - analyse
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: normal

analyse:
  stage: analyse
  script:
    - ./ci/style/line_limit.sh -e '^\./\.clang-tidy$' .
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Debug ..
    - cd ..
    - bash -c "clang-tidy-6.0 -p=build -warnings-as-errors='*' src/**/*.c"
    - cppcheck -q --enable=all --project=build/compile_commands.json
      --error-exitcode=1 --suppressions-list=.cppcheck-suppress

build:clang:
  stage: build
  script:
    - mkdir build
    - cd build
    - CC=clang-6.0 cmake ..
    - make

build:gcc:
  stage: build
  script:
    - mkdir build
    - cd build
    - CC=gcc cmake ..
    - make

test:clang:
  stage: test
  script:
    - mkdir build
    - cd build
    - CC=clang-6.0 CXX=clang++-6.0 cmake -DBUILD_TESTING:BOOL=ON ..
    - make
    - make test

test:gcc:
  stage: test
  script:
    - mkdir build
    - cd build
    - CC=gcc CXX=g++ cmake -DBUILD_TESTING:BOOL=ON ..
    - make
    - make test
